Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

In [5]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
print("The datatype of list is",type(list_))
array_list = np.array(object = list_)
print("The datatype of array_list is ",type(array_list))

The datatype of list is <class 'list'>
The datatype of array_list is  <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [9]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
for i in list_ :
    print("The datatype of list", i ,"is",type(i))
print("The datatype of list is ",type(list_))
array_list = np.array(object = list_)
for i in array_list :
    print("The datatype of ", i ," in array_list is ",type(i))
print("The datatype of array_list is ", type(array_list))

The datatype of list 1 is <class 'str'>
The datatype of list 2 is <class 'str'>
The datatype of list 3 is <class 'str'>
The datatype of list 4 is <class 'str'>
The datatype of list 5 is <class 'str'>
The datatype of list is  <class 'list'>
The datatype of  1  in array_list is  <class 'numpy.str_'>
The datatype of  2  in array_list is  <class 'numpy.str_'>
The datatype of  3  in array_list is  <class 'numpy.str_'>
The datatype of  4  in array_list is  <class 'numpy.str_'>
The datatype of  5  in array_list is  <class 'numpy.str_'>
The datatype of array_list is  <class 'numpy.ndarray'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [10]:
array_list = np.array(object = list_, dtype = int)

In [11]:
array_list

array([1, 2, 3, 4, 5])

In [12]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
for i in list_ :
    print("The datatype of list", i ,"is",type(i))
print("The datatype of list is ",type(list_))
array_list = np.array(object = list_,dtype=int)
for i in array_list :
    print("The datatype of ", i ," in array_list is ",type(i))
print("The datatype of array_list is ", type(array_list))

The datatype of list 1 is <class 'str'>
The datatype of list 2 is <class 'str'>
The datatype of list 3 is <class 'str'>
The datatype of list 4 is <class 'str'>
The datatype of list 5 is <class 'str'>
The datatype of list is  <class 'list'>
The datatype of  1  in array_list is  <class 'numpy.int64'>
The datatype of  2  in array_list is  <class 'numpy.int64'>
The datatype of  3  in array_list is  <class 'numpy.int64'>
The datatype of  4  in array_list is  <class 'numpy.int64'>
The datatype of  5  in array_list is  <class 'numpy.int64'>
The datatype of array_list is  <class 'numpy.ndarray'>


Yes there is chnage in datatype in the elements in list_ and array_list. Earlier elements in array_list was string and now it is int

Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [13]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [15]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [16]:
num_array.shape

(2, 3)

In [17]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [19]:
b=np.zeros((3,3))

In [20]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
b.shape

(3, 3)

In [22]:
b.size

9

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [25]:
e=np.eye(5,5,dtype=int)

In [26]:
e

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])