In [1]:
#Import numpy mathematical package
import numpy as np 

In [2]:
l=[1,2,3,4,5]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5])

In [4]:
type(np.array(l))

numpy.ndarray

In [5]:
#Upcasting
np.array([1,2,3.0])

array([1., 2., 3.])

In [6]:
np.array([1,2,3.5])

array([1. , 2. , 3.5])

In [8]:
#Pass more than one dimension
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
#Pass minimum dimension
np.array([1,2,3,4,5],ndmin=3)

array([[[1, 2, 3, 4, 5]]])

In [10]:
#Pass minimum dimension
np.array([1,2,3,4,5],ndmin=4)

array([[[[1, 2, 3, 4, 5]]]])

In [11]:
#Type provided
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
#Type provided
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [13]:
#Data-type consisting of more than one element:

#>>> x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
#>>> x['a']
#array([1, 3])

In [17]:
x=np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])

In [18]:
x

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i4')])

In [19]:
x['a']

array([1, 3], dtype=int32)

In [20]:
x['b']

array([2, 4], dtype=int32)

In [ ]:
Creating an array from sub-classes:

>>> np.array(np.mat('1 2; 3 4'))
array([[1, 2],
       [3, 4]])

>>> np.array(np.mat('1 2; 3 4'), subok=True)
matrix([[1, 2],
        [3, 4]])

In [21]:
np.array(np.mat('1 2;3 4'))

array([[1, 2],
       [3, 4]])

In [22]:
np.array(np.mat('1 2;3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

In [23]:
#Usage of asarray
np.asarray(l)

array([1, 2, 3, 4, 5])

In [24]:
type(np.asarray(l))

numpy.ndarray

In [ ]:
Existing arrays are not copied:

>>> a = np.array([1, 2])
>>> np.asarray(a) is a
True

In [25]:
a=np.asarray(l)

In [26]:
a

array([1, 2, 3, 4, 5])

In [27]:
np.asarray(a)

array([1, 2, 3, 4, 5])

In [28]:
np.asarray(a) is a

True

In [29]:
a.ndim

1

In [30]:
b=[[1,2,3],[4,5,6],[7,8,9]]

In [31]:
b=np.array(b)

In [32]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
b.ndim

2

In [34]:
c=[[[1,2],[3,4],[5,6],[7,8]]]

In [35]:
c=np.array(c)

In [37]:
c.ndim

3

In [38]:
c

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [39]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [40]:
type(np.matrix(l))

numpy.matrix

In [41]:
m=np.matrix(l)

In [42]:
type(m)

numpy.matrix

In [43]:
m.ndim

2

In [44]:
n=np.matrix([[1,2],[3,4]])

In [45]:
n

matrix([[1, 2],
        [3, 4]])

In [46]:
n.ndim

2

In [ ]:
Convert a list into an array:

>>> a = [1, 2]
>>> np.asanyarray(a)
array([1, 2])

In [47]:
a=[1,2]

In [49]:
np.asanyarray(a)

array([1, 2])

In [50]:
np.asanyarray(n)

matrix([[1, 2],
        [3, 4]])

In [51]:
type(np.asanyarray(n))

numpy.matrix

In [52]:
type(np.asanyarray(a))

numpy.ndarray

In [53]:
#Demonstrate Shallow copy
a

[1, 2]

In [102]:
array_a=np.array(a)

In [55]:
array_a

array([1, 2])

In [56]:
array_b=array_a

In [57]:
array_b

array([1, 2])

In [58]:
array_a

array([1, 2])

In [59]:
array_a[0]=100

In [60]:
array_a

array([100,   2])

In [61]:
array_b

array([100,   2])

In [62]:
#Deep Copy
array_c=np.copy(array_a)

In [63]:
array_a

array([100,   2])

In [64]:
array_c

array([100,   2])

In [65]:
array_c[0]=1

In [66]:
array_c

array([1, 2])

In [67]:
array_a

array([100,   2])

In [68]:
array_b

array([100,   2])

In [69]:
np.fromfunction(lambda i, j: i, (2, 2), dtype=float)

array([[0., 0.],
       [1., 1.]])

In [70]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [71]:
np.fromfunction(lambda i,j : i+j ,(2,2), dtype=int)

array([[0, 1],
       [1, 2]])

In [72]:
np.fromfunction(lambda i,j : i==j , (2,2))

array([[ True, False],
       [False,  True]])

In [74]:
np.fromfunction(lambda x,y : x*y ,(3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [76]:
for i in range(5) :
    print(i)

0
1
2
3
4


In [77]:
( i*i for i in range(5))

<generator object <genexpr> at 0x7f107359ac70>

In [78]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [79]:
iterable=(i*i for i in range(5))

In [80]:
np.fromiter(iterable,dtype=int)

array([ 0,  1,  4,  9, 16])

In [ ]:
>>> iterable = ((x+1, x+2) for x in range(5))
>>> np.fromiter(iterable, dtype=np.dtype((int, 2)))
array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [81]:
list((x+1,x+2) for x in range(5))

[(1, 2), (2, 3), (3, 4), (4, 5), (5, 6)]

In [95]:
iterable=((x+1,x+2) for x in range(5))

In [88]:
np.fromiter(iterable, dtype=np.dtype((int,2)))

array([[4, 5],
       [5, 6]])

In [89]:
import numpy as np

In [91]:
np.array([1,2])

array([1, 2])

In [92]:
np.dtype(np.int16)

dtype('int16')

In [93]:
np.dtype((int,2))

dtype(('<i8', (2,)))

In [97]:
np.fromiter(iterable, dtype=np.dtype((np.int16,2)))

array([[2, 3],
       [3, 4],
       [4, 5],
       [5, 6]], dtype=int16)

In [98]:
np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

In [99]:
np.fromstring('1 2 3 4 5',dtype=int,sep=' ')

array([1, 2, 3, 4, 5])

In [106]:
a=np.fromstring('1,2,3,4,5',dtype=int,sep=',')

In [101]:
arr

NameError: name 'arr' is not defined

In [103]:
array_a.ndim

1

In [104]:
array_a.size

2

In [105]:
array_a

array([1, 2])

In [107]:
a.ndim

1

In [108]:
a.size

5

In [109]:
a

array([1, 2, 3, 4, 5])

In [110]:
a.shape

(5,)

In [111]:
array_a.shape

(2,)

In [112]:
array_a

array([1, 2])

In [113]:
b=np.array([[1,2],[3,4],[5,6]])

In [114]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
b.shape

(3, 2)

In [116]:
b.size

6

In [117]:
b.ndim

2

In [118]:
range(5)

range(0, 5)

In [119]:
list(range(5))

[0, 1, 2, 3, 4]

In [120]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [121]:
list(range(1.4,8.8))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
Examples
--------
>>> np.arange(3)
array([0, 1, 2])
>>> np.arange(3.0)
array([ 0.,  1.,  2.])
>>> np.arange(3,7)
array([3, 4, 5, 6])
>>> np.arange(3,7,2)
array([3, 5])

In [122]:
np.arange(3)

array([0, 1, 2])

In [124]:
np.arange(0.4,8.8,0.25)

array([0.4 , 0.65, 0.9 , 1.15, 1.4 , 1.65, 1.9 , 2.15, 2.4 , 2.65, 2.9 ,
       3.15, 3.4 , 3.65, 3.9 , 4.15, 4.4 , 4.65, 4.9 , 5.15, 5.4 , 5.65,
       5.9 , 6.15, 6.4 , 6.65, 6.9 , 7.15, 7.4 , 7.65, 7.9 , 8.15, 8.4 ,
       8.65])

In [126]:
np.linspace(2,3,num=20)

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [127]:
np.linspace(2,3,9)

array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ])

In [128]:
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [ ]:
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
       [ 0.]])

>>> s = (2,2)
>>> np.zeros(s)
array([[ 0.,  0.],
       [ 0.,  0.]])

>>> np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype
array([(0, 0), (0, 0)],
      dtype=[('x', '<i4'), ('y', '<i4')])

In [129]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [130]:
np.zeros(5 ,dtype=int)

array([0, 0, 0, 0, 0])

In [132]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [133]:
s=(2,2)

In [134]:
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [139]:
a= np.zeros((3,4,2,3))

In [138]:
a.ndim

3

In [140]:
a

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [141]:
a.ndim

4

In [142]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [144]:
b=np.ones((3,4,2))

In [145]:
b.ndim

3

In [146]:
b+3

array([[[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]]])

In [147]:
b*3

array([[[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]]])

In [148]:
b*100

array([[[100., 100.],
        [100., 100.],
        [100., 100.],
        [100., 100.]],

       [[100., 100.],
        [100., 100.],
        [100., 100.],
        [100., 100.]],

       [[100., 100.],
        [100., 100.],
        [100., 100.],
        [100., 100.]]])

In [149]:
np.empty([1,1])

array([[100.]])

In [150]:
np.empty([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [151]:
>>> np.eye(2, dtype=int)
array([[1, 0],
       [0, 1]])
>>> np.eye(3, k=1)
array([[0.,  1.,  0.],
       [0.,  0.,  1.],
       [0.,  0.,  0.]])


NameError: name 'array' is not defined

In [154]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [155]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [156]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [157]:
np.eye(3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [158]:
np.eye(3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [161]:
#Convert Array into Dataframe
a=np.eye(3,dtype=int)

In [162]:
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [163]:
import pandas as pd

In [164]:
pd.DataFrame(a)

0  1  2
0  1  0  0
1  0  1  0
2  0  0  1

In [165]:
np.random(5)

TypeError: 'module' object is not callable

In [166]:
np.random.rand(5)

array([0.12726403, 0.19826228, 0.44293991, 0.59470515, 0.39768152])

In [168]:
np.random.rand(2,3)

array([[0.26544336, 0.63026785, 0.01139306],
       [0.60329503, 0.73664052, 0.36441584]])

In [169]:
np.random.randn(2,3)

array([[ 0.01625105, -0.19013613, -0.6135695 ],
       [ 0.78995189,  0.21021139,  1.97553316]])

In [170]:
#Standard Normal Distribution
# SD=1 ; Mean =0
np.random.randn()

-0.15295881616700635

In [171]:
np.random.rand()

0.05098177010361493

In [ ]:
>>> np.random.randint(2, size=10)
array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0]) # random
>>> np.random.randint(1, size=10)
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Generate a 2 x 4 array of ints between 0 and 4, inclusive:

>>> np.random.randint(5, size=(2, 4))
array([[4, 0, 2, 1], # random
       [3, 2, 2, 0]])

Generate a 1 x 3 array with 3 different upper bounds

>>> np.random.randint(1, [3, 5, 10])
array([2, 2, 9]) # random

Generate a 1 by 3 array with 3 different lower bounds

>>> np.random.randint([1, 5, 7], 10)
array([9, 8, 7]) # random

Generate a 2 by 4 array using broadcasting with dtype of uint8

>>> np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
array([[ 8,  6,  9,  7], # random
       [ 1, 16,  9, 12]], dtype=uint8)
Type:      builtin_function_or_method


In [172]:
np.random.randint(2, size=10)


array([1, 0, 1, 1, 0, 1, 1, 0, 0, 1])

In [174]:
np.ndim

<function numpy.ndim(a)>

In [175]:
np.random.randint(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [177]:
np.random.randint(8,size=(2,4))

array([[3, 1, 4, 6],
       [0, 1, 4, 4]])

In [181]:
arr2=np.random.randint(3,5,(3,4))

In [182]:
arr2

array([[3, 3, 3, 3],
       [4, 3, 3, 4],
       [3, 3, 4, 4]])

In [183]:
arr2.size

12

In [184]:
arr2.shape

(3, 4)

In [185]:
arr2.reshape(4,3)

array([[3, 3, 3],
       [3, 4, 3],
       [3, 4, 3],
       [3, 4, 4]])

In [186]:
arr2.shape

(3, 4)

In [187]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [189]:
arr2.reshape(6,2)

array([[3, 3],
       [3, 3],
       [4, 3],
       [3, 4],
       [3, 3],
       [4, 4]])

In [191]:
arr3=arr2.reshape(1,-5)

In [192]:
arr3.shape

(1, 12)

In [193]:
arr10=np.random.randint(1,10,(5,6))

In [194]:
arr10

array([[7, 2, 7, 2, 6, 1],
       [9, 8, 1, 8, 1, 8],
       [3, 9, 8, 7, 5, 2],
       [6, 6, 3, 9, 2, 5],
       [5, 3, 2, 9, 5, 6]])

In [195]:
arr10 > 3

array([[ True, False,  True, False,  True, False],
       [ True,  True, False,  True, False,  True],
       [False,  True,  True,  True,  True, False],
       [ True,  True, False,  True, False,  True],
       [ True, False, False,  True,  True,  True]])

In [196]:
arr10[arr10>3]

array([7, 7, 6, 9, 8, 8, 8, 9, 8, 7, 5, 6, 6, 9, 5, 5, 9, 5, 6])

In [197]:
arr10

array([[7, 2, 7, 2, 6, 1],
       [9, 8, 1, 8, 1, 8],
       [3, 9, 8, 7, 5, 2],
       [6, 6, 3, 9, 2, 5],
       [5, 3, 2, 9, 5, 6]])

In [202]:
arr10[3:,[4,5]]

array([[2, 5],
       [5, 6]])

In [205]:
arr10[2:4,[2,3]]

array([[8, 7],
       [3, 9]])

In [206]:
arr1=np.random.randint(1,3,(3,3))

In [207]:
arr2=np.random.randint(1,3,(3,3))

In [208]:
arr1

array([[1, 2, 1],
       [1, 2, 2],
       [1, 1, 1]])

In [209]:
arr2

array([[1, 2, 1],
       [1, 2, 1],
       [2, 1, 1]])

In [210]:
arr1+arr2

array([[2, 4, 2],
       [2, 4, 3],
       [3, 2, 2]])

In [211]:
arr1 - arr2

array([[ 0,  0,  0],
       [ 0,  0,  1],
       [-1,  0,  0]])

In [212]:
arr1 * arr2

array([[1, 4, 1],
       [1, 4, 2],
       [2, 1, 1]])

In [213]:
arr1@arr2

array([[5, 7, 4],
       [7, 8, 5],
       [4, 5, 3]])

In [214]:
arr1

array([[1, 2, 1],
       [1, 2, 2],
       [1, 1, 1]])

In [215]:
arr2

array([[1, 2, 1],
       [1, 2, 1],
       [2, 1, 1]])

In [216]:
arr1=np.random.randint(1,3,(2,2))

In [217]:
arr2=np.random.randint(1,3,(2,2))

In [218]:
arr1

array([[2, 1],
       [2, 2]])

In [219]:
arr2

array([[1, 1],
       [2, 1]])

In [220]:
arr1@arr2

array([[4, 3],
       [6, 4]])

In [221]:
arr1/arr2

array([[2., 1.],
       [1., 2.]])

In [222]:
arr1/0

/tmp/ipykernel_70/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf],
       [inf, inf]])

In [233]:
arr1=np.zeros((3,4))

arr1

In [226]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [227]:
arr2=np.array([1,2,3])

In [228]:
arr2

array([1, 2, 3])

In [229]:
arr1+arr2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [231]:
arr3=np.array([[1,1,1]])

In [234]:
arr1+arr3

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [235]:
arr1+arr3.T

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [236]:
arr2.T

array([1, 2, 3])

In [237]:
arr2

array([1, 2, 3])

In [238]:
np.sqrt(arr1)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [239]:
np.min(arr1)

0.0

In [240]:
np.max(arr1)

0.0

In [4]:
arr=np.random.randint(1,10,(4,4))

In [2]:
import numpy as np

In [5]:
arr

array([[7, 6, 5, 3],
       [9, 2, 8, 1],
       [8, 5, 4, 3],
       [5, 9, 4, 4]])

In [6]:
arr.reshape(8,2)

array([[7, 6],
       [5, 3],
       [9, 2],
       [8, 1],
       [8, 5],
       [4, 3],
       [5, 9],
       [4, 4]])

In [7]:
arr.T

array([[7, 9, 8, 5],
       [6, 2, 5, 9],
       [5, 8, 4, 4],
       [3, 1, 3, 4]])

In [8]:
arr.flatten()

array([7, 6, 5, 3, 9, 2, 8, 1, 8, 5, 4, 3, 5, 9, 4, 4])

In [9]:
arr.expand_dims(arr,axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'expand_dims'

In [10]:
np.expand_dims(arr,axis=1)

array([[[7, 6, 5, 3]],

       [[9, 2, 8, 1]],

       [[8, 5, 4, 3]],

       [[5, 9, 4, 4]]])

In [11]:
arr

array([[7, 6, 5, 3],
       [9, 2, 8, 1],
       [8, 5, 4, 3],
       [5, 9, 4, 4]])

In [14]:
arr1=np.expand_dims(arr,axis=0)

In [13]:
arr.ndim

2

In [15]:
arr1.ndim

3

In [19]:
data=np.array([[1], [2], [3], [4], [5]])

In [20]:
data

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [21]:
np.squeeze(data)

array([1, 2, 3, 4, 5])

In [22]:
x = np.array([[1234]])

In [23]:
x

array([[1234]])

In [24]:
np.squeeze(x)

array(1234)

In [25]:
x.ndim

2

In [26]:
np.squeeze(x).ndim

0

In [27]:
np.repeat(1,5)

array([1, 1, 1, 1, 1])

In [28]:
np.roll(data,2)

array([[4],
       [5],
       [1],
       [2],
       [3]])

In [29]:
data

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [31]:
np.roll(data,4)

array([[2],
       [3],
       [4],
       [5],
       [1]])

In [33]:
np.diag(np.array((1,2,3,4)))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:
arr1=np.random.randint(1,10,(3,3))

In [35]:
arr2=np.random.randint(1,10,(3,3))

In [36]:
arr1

array([[5, 3, 9],
       [1, 8, 7],
       [3, 7, 5]])

In [37]:
arr2

array([[5, 9, 6],
       [6, 2, 1],
       [3, 5, 1]])

In [38]:
arr1+arr2

array([[10, 12, 15],
       [ 7, 10,  8],
       [ 6, 12,  6]])

In [39]:
arr1**arr2

array([[  3125,  19683, 531441],
       [     1,     64,      7],
       [    27,  16807,      5]])

In [40]:
np.array(["Lalitha","AdiYogi"])

array(['Lalitha', 'AdiYogi'], dtype='<U7')

In [41]:
np.char.upper(["Lalitha","AdiYogi"])

array(['LALITHA', 'ADIYOGI'], dtype='<U7')

In [42]:
np.cos(arr1)

array([[ 0.28366219, -0.9899925 , -0.91113026],
       [ 0.54030231, -0.14550003,  0.75390225],
       [-0.9899925 ,  0.75390225,  0.28366219]])

In [43]:
np.power(arr1,2)

array([[25,  9, 81],
       [ 1, 64, 49],
       [ 9, 49, 25]])

In [44]:
arr1

array([[5, 3, 9],
       [1, 8, 7],
       [3, 7, 5]])

In [45]:
np.mod(arr1)

TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given

In [46]:
np.median(arr1)

5.0

In [47]:
np.min(arr1)

1

In [48]:
np.max(arr1)

9

In [49]:
np.mean(arr1)

5.333333333333333

In [50]:
np.std(arr1)

2.494438257849294

In [51]:
arr=np.array([2,3,4,67,1])

In [52]:
arr

array([ 2,  3,  4, 67,  1])

In [53]:
np.sort(arr)

array([ 1,  2,  3,  4, 67])

In [54]:
np.searchsorted(arr,6)

5

In [55]:
arr

array([ 2,  3,  4, 67,  1])

In [56]:
np.searchsorted(arr,100)

5

In [57]:
np.count_nonzero(arr)

5

In [60]:
np.where(arr>1)

(array([0, 1, 2, 3]),)

In [62]:
np.extract(arr,arr>2)

array([False,  True,  True,  True, False])

In [63]:
arr

array([ 2,  3,  4, 67,  1])

In [65]:
arr.byteswap(True)

array([ 144115188075855872,  216172782113783808,  288230376151711744,
       4827858800541171712,   72057594037927936])

In [66]:
arr

array([ 144115188075855872,  216172782113783808,  288230376151711744,
       4827858800541171712,   72057594037927936])

In [69]:
b=arr1.view()

In [70]:
b

array([[5, 3, 9],
       [1, 8, 7],
       [3, 7, 5]])

In [71]:
b[0]=123

In [72]:
b

array([[123, 123, 123],
       [  1,   8,   7],
       [  3,   7,   5]])

In [73]:
arr1

array([[123, 123, 123],
       [  1,   8,   7],
       [  3,   7,   5]])

In [74]:
import numpy.matlib as nm

In [78]:
nm.zeros((2,3))

matrix([[0., 0., 0.],
        [0., 0., 0.]])

In [79]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
np.argsort(